name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
          cache: pnpm

      - name: Install
        run: pnpm i --frozen-lockfile=false

      - name: Typecheck
        run: pnpm -w typecheck

      - name: Lint
        run: pnpm -w lint

      - name: Unit tests
        run: pnpm -w test

      - name: Build web
        run: pnpm --filter @fleetops/web build